name: CI Workflow
on:
  pull_request:
jobs:
  ci-workflow:
    name: CI
    uses: Leuchtfeuer/mautic-ci-runner/.github/workflows/complete-ci.yaml@mtc-10784-fix-cr
    with:
      skipCodeReview: true
    secrets:
      PERSONAL_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}